const data = [
    ["Elementární funkce a jejich vlastnosti", "23", "4", "f1"],
    ["Elementární funkce a jejich vlastnosti", "23", "4", "f2"],
    ["Elementární funkce a jejich vlastnosti", "23", "4", "f3"],
    ["Elementární funkce a jejich vlastnosti", "23", "4", "f4"],
    ["Elementární funkce a jejich vlastnosti", "23", "4", "f5"],
    ["Elementární funkce a jejich vlastnosti", "23", "4", "f6"],
    ["Elementární funkce a jejich vlastnosti", "23", "4", "f10"],
    ["Elementární funkce a jejich vlastnosti", "23", "4", "f11"],
    ["Elementární funkce a jejich vlastnosti", "23", "4", "f12"],
    ["Elementární funkce a jejich vlastnosti", "23", "4", "f13"],
    ["Elementární funkce a jejich vlastnosti", "23", "4", "f14"],
    ["Elementární funkce a jejich vlastnosti", "24", "11", ""],
    ["Elementární funkce a jejich vlastnosti", "25", "23", "h3"],
    ["Elementární funkce a jejich vlastnosti", "23", "23", "h6"],
    ["Elementární funkce a jejich vlastnosti", "23", "23", "h9"],
    ["Elementární funkce a jejich vlastnosti", "23", "23", "h10"],
    ["Elementární funkce a jejich vlastnosti", "23", "23", "h11"],
    ["Elementární funkce a jejich vlastnosti", "23", "23", "h12"],
    ["Elementární funkce a jejich vlastnosti", "27", "30", ""],
    ["Elementární funkce a jejich vlastnosti", "27", "31", ""],
    ["Elementární funkce a jejich vlastnosti", "28", "40", "f4"],
    ["Elementární funkce a jejich vlastnosti", "28", "40", "m2"],
    ["Elementární funkce a jejich vlastnosti", "28", "40", "g2"],
    ["Elementární funkce a jejich vlastnosti", "28", "40", "g3"],
    ["Elementární funkce a jejich vlastnosti", "28", "40", "g4"],
    ["Elementární funkce a jejich vlastnosti", "28", "41", "b"],
    ["Elementární funkce a jejich vlastnosti", "29", "46", ""],
    ["Elementární funkce a jejich vlastnosti", "29", "47", ""],
    ["Elementární funkce a jejich vlastnosti", "29", "48", ""],
    ["Elementární funkce a jejich vlastnosti", "29", "49", ""],
    ["Elementární funkce a jejich vlastnosti", "29", "50", ""],
    ["Elementární funkce a jejich vlastnosti", "29", "54", "f1"],
    ["Elementární funkce a jejich vlastnosti", "29", "54", "f3"],
    ["Elementární funkce a jejich vlastnosti", "29", "54", "f7"],
    ["Elementární funkce a jejich vlastnosti", "29", "54", "f9"],
    ["Elementární funkce a jejich vlastnosti", "29", "55", "g4"],
    ["Elementární funkce a jejich vlastnosti", "29", "55", "h4"],
    ["Elementární funkce a jejich vlastnosti", "29", "55", "k3"],
    ["Elementární funkce a jejich vlastnosti", "29", "55", "k4"],
    ["Elementární funkce a jejich vlastnosti", "30", "57"],
    ["Elementární funkce a jejich vlastnosti", "30", "58"],
    ["Elementární funkce a jejich vlastnosti", "30", "64"],
    ["Elementární funkce a jejich vlastnosti", "30", "65"],
    ["Elementární funkce a jejich vlastnosti", "30", "66", "f3"],
    ["Elementární funkce a jejich vlastnosti", "30", "66", "f7"],
    ["Elementární funkce a jejich vlastnosti", "30", "66", "f9"],
    ["Elementární funkce a jejich vlastnosti", "30", "66", "f4"],
    ["Elementární funkce a jejich vlastnosti", "30", "66", "f5"],
    ["Elementární funkce a jejich vlastnosti", "32", "76"],
    ["Elementární funkce a jejich vlastnosti", "32", "77"],
    ["Elementární funkce a jejich vlastnosti", "32", "78", "f2"],
    ["Elementární funkce a jejich vlastnosti", "32", "78", "f3"],
    ["Elementární funkce a jejich vlastnosti", "32", "78", "f4"],
    ["Elementární funkce a jejich vlastnosti", "32", "78", "f5"],
    ["Elementární funkce a jejich vlastnosti", "32", "78", "f6"],
    ["Elementární funkce a jejich vlastnosti", "32", "81"],
    ["Elementární funkce a jejich vlastnosti", "32", "83", "g1"],
    ["Elementární funkce a jejich vlastnosti", "32", "83", "g4"],
    ["Elementární funkce a jejich vlastnosti", "32", "83", "g5"],
    ["Elementární funkce a jejich vlastnosti", "32", "83", "g6"],
    ["Elementární funkce a jejich vlastnosti", "32", "84", "h1"],
    ["Elementární funkce a jejich vlastnosti", "32", "84", "h2"],
    ["Elementární funkce a jejich vlastnosti", "32", "84", "h3"],
    ["Elementární funkce a jejich vlastnosti", "41", "15", "f5"],
    ["Elementární funkce a jejich vlastnosti", "41", "15", "f6"],
    ["Elementární funkce a jejich vlastnosti", "41", "15", "f7"],
    ["Elementární funkce a jejich vlastnosti", "41", "15", "f8"],
    ["Elementární funkce a jejich vlastnosti", "41", "15", "f9"],
    ["Elementární funkce a jejich vlastnosti", "41", "16", "g5"],
    ["Elementární funkce a jejich vlastnosti", "41", "16", "g6"],
    ["Elementární funkce a jejich vlastnosti", "41", "16", "g7"],
    ["Elementární funkce a jejich vlastnosti", "41", "16", "g8"],
    ["Elementární funkce a jejich vlastnosti", "41", "16", "g9"],
    ["Elementární funkce a jejich vlastnosti", "41", "17", "h1"],
    ["Elementární funkce a jejich vlastnosti", "41", "17", "h2"],
    ["Elementární funkce a jejich vlastnosti", "42", "27", "f3"],
    ["Elementární funkce a jejich vlastnosti", "42", "27", "f4"],
    ["Elementární funkce a jejich vlastnosti", "42", "27", "f5"],
    ["Elementární funkce a jejich vlastnosti", "42", "27", "f6"],
    ["Elementární funkce a jejich vlastnosti", "42", "27", "f7"],
    ["Elementární funkce a jejich vlastnosti", "42", "27", "f8"],
    ["Elementární funkce a jejich vlastnosti", "42", "27", "f9"],
    ["Elementární funkce a jejich vlastnosti", "43", "28", "g3"],
    ["Elementární funkce a jejich vlastnosti", "43", "28", "g6"],
    ["Elementární funkce a jejich vlastnosti", "43", "32", "f8"],
    ["Elementární funkce a jejich vlastnosti", "43", "32", "f9"],
    ["Elementární funkce a jejich vlastnosti", "43", "33", "g5"],
    ["Elementární funkce a jejich vlastnosti", "43", "33", "g8"],
    ["Elementární funkce a jejich vlastnosti", "43", "34", "f5"],
    ["Elementární funkce a jejich vlastnosti", "43", "34", "f6"],
    ["Elementární funkce a jejich vlastnosti", "43", "35", "g6"],
    ["Elementární funkce a jejich vlastnosti", "43", "35", "g8"],
    ["Elementární funkce a jejich vlastnosti", "43", "37", "g4"],
    ["Elementární funkce a jejich vlastnosti", "43", "37", "g6"],
    ["Elementární funkce a jejich vlastnosti", "44", "37", "g4"],
    ["Algebraické rovnice, výrazy a mocniny", "12", "2", "a"],
    ["Algebraické rovnice, výrazy a mocniny", "12", "2", "b"],
    ["Algebraické rovnice, výrazy a mocniny", "12", "2", "e"],
    ["Algebraické rovnice, výrazy a mocniny", "12", "2", "f"],
    ["Algebraické rovnice, výrazy a mocniny", "12", "3", "b"],
    ["Algebraické rovnice, výrazy a mocniny", "12", "3", "e"],
    ["Algebraické rovnice, výrazy a mocniny", "13", "6", "e"],
    ["Algebraické rovnice, výrazy a mocniny", "13", "6", "d"],
    ["Algebraické rovnice, výrazy a mocniny", "13", "7", ""],
    ["Algebraické rovnice, výrazy a mocniny", "13", "8", ""],
    ["Algebraické rovnice, výrazy a mocniny", "13", "9", ""],
    ["Algebraické rovnice, výrazy a mocniny", "13", "10", ""],
    ["Algebraické rovnice, výrazy a mocniny", "13", "11", ""],
    ["Algebraické rovnice, výrazy a mocniny", "13", "12", ""],
    ["Algebraické rovnice, výrazy a mocniny", "13", "16", "b"],
    ["Algebraické rovnice, výrazy a mocniny", "14", "18", "b"],
    ["Algebraické rovnice, výrazy a mocniny", "14", "18", "c"],
    ["Algebraické rovnice, výrazy a mocniny", "14", "19", "d"],
    ["Algebraické rovnice, výrazy a mocniny", "14", "19", "e"],
    ["Algebraické rovnice, výrazy a mocniny", "14", "20", "h"],
    ["Algebraické rovnice, výrazy a mocniny", "14", "20", "i"],
    ["Algebraické rovnice, výrazy a mocniny", "14", "20", "j"],
    ["Algebraické rovnice, výrazy a mocniny", "14", "21", ""],
    ["Algebraické rovnice, výrazy a mocniny", "15", "22", "q"],
    ["Algebraické rovnice, výrazy a mocniny", "15", "22", "r"],
    ["Algebraické rovnice, výrazy a mocniny", "15", "22", "t"],
    ["Algebraické rovnice, výrazy a mocniny", "15", "22", "u"],
    ["Algebraické rovnice, výrazy a mocniny", "15", "22", "v"],
    ["Algebraické rovnice, výrazy a mocniny", "15", "23", "a"],
    ["Algebraické rovnice, výrazy a mocniny", "15", "23", "b"],
    ["Algebraické rovnice, výrazy a mocniny", "15", "23", "h"],
    ["Algebraické rovnice, výrazy a mocniny", "15", "23", "j"],
    ["Algebraické rovnice, výrazy a mocniny", "15", "23", "l"],
    ["Algebraické rovnice, výrazy a mocniny", "29", "56", ""],
    ["Algebraické rovnice, výrazy a mocniny", "57", "2", ""],
    ["Algebraické rovnice, výrazy a mocniny", "57", "3", ""],
    ["Algebraické rovnice, výrazy a mocniny", "57", "5", "m3"],
    ["Algebraické rovnice, výrazy a mocniny", "57", "5", "m4"],
    ["Algebraické rovnice, výrazy a mocniny", "57", "5", "m5"],
    ["Algebraické rovnice, výrazy a mocniny", "57", "5", "m6"],
    ["Algebraické rovnice, výrazy a mocniny", "58", "9", "f5"],
    ["Algebraické rovnice, výrazy a mocniny", "58", "9", "f6"],
    ["Algebraické rovnice, výrazy a mocniny", "58", "9", "f10"],
    ["Algebraické rovnice, výrazy a mocniny", "58", "9", "f11"],
    ["Algebraické rovnice, výrazy a mocniny", "58", "9", "f12"],
    ["Algebraické rovnice, výrazy a mocniny", "58", "10", "g2"],
    ["Algebraické rovnice, výrazy a mocniny", "58", "10", "g3"],
    ["Algebraické rovnice, výrazy a mocniny", "58", "10", "g4"],
    ["Algebraické rovnice, výrazy a mocniny", "58", "10", "g5"],
    ["Algebraické rovnice, výrazy a mocniny", "58", "15", ""],
    ["Algebraické rovnice, výrazy a mocniny", "60", "26", "j"],
    ["Algebraické rovnice, výrazy a mocniny", "60", "26", "k"],
    ["Algebraické rovnice, výrazy a mocniny", "60", "26", "l"],
    ["Algebraické rovnice, výrazy a mocniny", "61", "35", "d"],
    ["Algebraické rovnice, výrazy a mocniny", "61", "35", "e"],
    ["Algebraické rovnice, výrazy a mocniny", "61", "35", "f"],
    ["Algebraické rovnice, výrazy a mocniny", "61", "35", "g"],
    ["Algebraické rovnice, výrazy a mocniny", "61", "36", ""],
    ["Algebraické rovnice, výrazy a mocniny", "62", "43", "d"],
    ["Algebraické rovnice, výrazy a mocniny", "62", "43", "e"],
    ["Algebraické rovnice, výrazy a mocniny", "62", "43", "f"],
    ["Algebraické rovnice, výrazy a mocniny", "62", "44", "a"],
    ["Algebraické rovnice, výrazy a mocniny", "62", "44", "c"],
    ["Algebraické rovnice, výrazy a mocniny", "63", "47", ""],
    ["Algebraické rovnice, výrazy a mocniny", "63", "52", "e"],
    ["Algebraické rovnice, výrazy a mocniny", "63", "52", "f"],
    ["Algebraické rovnice, výrazy a mocniny", "63", "53", "g"],
  ["Algebraické rovnice, výrazy a mocniny", "63", "53", "h"],
  ["Algebraické rovnice, výrazy a mocniny", "64", "54", "e"],
  ["Algebraické rovnice, výrazy a mocniny", "64", "54", "g"],
  ["Algebraické rovnice, výrazy a mocniny", "64", "54", "h"],
  ["Algebraické rovnice, výrazy a mocniny", "64", "56"],
  ["Algebraické rovnice, výrazy a mocniny", "64", "57", "c"],
  ["Algebraické rovnice, výrazy a mocniny", "64", "57", "d"],
  ["Algebraické rovnice, výrazy a mocniny", "64", "58"],
  ["Algebraické rovnice, výrazy a mocniny", "65", "60", "g2"],
  ["Algebraické rovnice, výrazy a mocniny", "65", "60", "g4"],
  ["Složitejší rovnice a jejich soustavy", "15", "24", "b"],
  ["Složitejší rovnice a jejich soustavy", "15", "24", "c"],
  ["Složitejší rovnice a jejich soustavy", "15", "24", "d"],
  ["Složitejší rovnice a jejich soustavy", "15", "25", "c"],
  ["Složitejší rovnice a jejich soustavy", "15", "25", "d"],
  ["Složitejší rovnice a jejich soustavy", "15", "26", "c"],
  ["Složitejší rovnice a jejich soustavy", "15", "27", "c"],
  ["Složitejší rovnice a jejich soustavy", "15", "27", "d"],
  ["Složitejší rovnice a jejich soustavy", "16", "31", "b"],
  ["Složitejší rovnice a jejich soustavy", "16", "31", "e"],
  ["Složitejší rovnice a jejich soustavy", "16", "31", "f"],
  ["Složitejší rovnice a jejich soustavy", "17", "33", "c"],
  ["Složitejší rovnice a jejich soustavy", "17", "33", "f"],
  ["Složitejší rovnice a jejich soustavy", "17", "33", "h"],
  ["Složitejší rovnice a jejich soustavy", "17", "33", "j"],
  ["Složitejší rovnice a jejich soustavy", "17", "33", "l"],
  ["Složitejší rovnice a jejich soustavy", "17", "34", "c"],
  ["Složitejší rovnice a jejich soustavy", "17", "36", "b"],
  ["Složitejší rovnice a jejich soustavy", "17", "37", "c"],
  ["Složitejší rovnice a jejich soustavy", "17", "37", "d"],
  ["Složitejší rovnice a jejich soustavy", "18", "38", "f"],
  ["Složitejší rovnice a jejich soustavy", "18", "38", "h"],
  ["Složitejší rovnice a jejich soustavy", "18", "38", "i"],
["Složitejší rovnice a jejich soustavy", "18", "38", "j"],
["Složitejší rovnice a jejich soustavy", "18", "39"],
["Složitejší rovnice a jejich soustavy", "18", "40"],
["Složitejší rovnice a jejich soustavy", "21", "2"],
["Složitejší rovnice a jejich soustavy", "21", "5", "b"],
["Složitejší rovnice a jejich soustavy", "21", "5", "c"],
["Složitejší rovnice a jejich soustavy", "21", "5", "d"],
["Složitejší rovnice a jejich soustavy", "21", "6", "a"],
["Složitejší rovnice a jejich soustavy", "21", "6", "b"],
["Složitejší rovnice a jejich soustavy", "21", "6", "c"],
["Složitejší rovnice a jejich soustavy", "22", "11"],
["Složitejší rovnice a jejich soustavy", "22", "12"],
["Složitejší rovnice a jejich soustavy", "22", "13"],
["Složitejší rovnice a jejich soustavy", "22", "14"],
["Složitejší rovnice a jejich soustavy", "22", "20", "a"],
["Složitejší rovnice a jejich soustavy", "22", "20", "b"],
["Exponenciální a logaritmické rovnice a nerovnice", "34", "1", "c"]
  ];
  
  function generateRandomRow() {
    const randomIndex = Math.floor(Math.random() * data.length);
    const randomRow = data[randomIndex];
    const randomRow_z=["Téma: "+ randomRow[0],"Stránka: " + randomRow[1],"Cvičení: "+ randomRow[2],"Příklad: "+ randomRow[3]];
    const randomRowString = randomRow_z.join(", ");
    document.getElementById("random-row").innerHTML = randomRowString;
  }